# Structurelint configuration for Python Refactor MCP
# Enforces clean project structure and organization for Python MCP server

root: true

exclude:
  # Version control
  - .git/**
  - .github/**

  # Python artifacts
  - __pycache__/**
  - .pytest_cache/**
  - "*.pyc"
  - "*.pyo"
  - "*.egg-info"

  # Virtual environments
  - venv/**
  - .venv/**
  - env/**

  # Build artifacts
  - dist/**
  - build/**

  # IDE
  - .vscode/**
  - .idea/**

rules:
  # Phase 0: Basic filesystem rules
  max-depth:
    max: 5

  max-files-in-dir:
    max: 20

  max-subdirs:
    max: 10

  # Python naming conventions - snake_case for everything
  naming-convention:
    "**/*.py": "snake_case"
    "**/": "snake_case"

  # Documentation requirements - every directory should have a README
  file-existence:
    "README.md": "exists:1"

  # Disallow temporary and problematic files
  disallowed-patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    - "Thumbs.db"
    - "**/*.swp"
    - "**/__pycache__"
    - "**/*.pyc"
    - "**/*.pyo"
    - "**/.pytest_cache"

  # Phase 3: Test File Validation
  # All Python modules should have corresponding test files
  test-adjacency:
    pattern: "separate"
    test-dir: "tests"
    file-patterns:
      - "src/**/*.py"
      - "tests/**/*.py"      # Also match test files for validation
    exemptions:
      - "**/__init__.py"      # Package initializers don't need tests

  test-location:
    integration-test-dir: "tests"
    allow-adjacent: false
    file-patterns:
      - "**/*_test.py"
      - "**/test_*.py"
    exemptions:
      - "testdata/**"
      - "example_project/**"

# Overrides for specific directories
overrides:
  # Source code in src/ - stricter rules
  - files: ['src/**']
    rules:
      max-depth: { max: 4 }
      max-files-in-dir: { max: 15 }

  # Tests can be more flexible
  - files: ['tests/**']
    rules:
      max-depth: { max: 5 }
      max-files-in-dir: { max: 25 }

  # Root level can have more files (configs, docs, etc.)
  - files: ['.']
    rules:
      max-files-in-dir: { max: 30 }

# Phase 1: Architectural layers
# This MCP server has a simple architecture
layers:
  - name: mcp_server
    path: src/python_refactor_mcp/**
    dependsOn: []

# Phase 2: Dead code detection
# Define entry points for the application
entrypoints:
  - src/python_refactor_mcp/__main__.py
  - "tests/**/*.py"
